#!/bin/bash
# Put it to /usr/local/bin/ and make it executable.
if [ "$1" == "" ]; then
  sudo iptables -t nat -S | perl -lne 'print $1 if m#^-A goodwin_prerouting -s 192.168.40.170/32 -j DNAT --to-destination (\d+\.\d+\.\d+\.\d+)\s*$#'
else
  sudo iptables -t nat -F goodwin_prerouting
  sudo iptables -t nat -F goodwin_postrouting

  sudo iptables -t nat -A goodwin_prerouting  -s 192.168.40.170 -j DNAT --to-destination $1
  sudo iptables -t nat -A goodwin_postrouting -d 192.168.40.170 -j SNAT --to-source 192.168.40.172
  sudo iptables -t nat -A goodwin_postrouting -d $1 -s 192.168.40.170 -p tcp -m multiport --dports 1501,1502 -j SNAT --to-source      192.168.40.172
  sudo iptables -t nat -A goodwin_prerouting  -s $1 -d 192.168.40.172 -p tcp -m multiport --sports 1501,1502 -j DNAT --to-destination 192.168.40.170

  sudo iptables -t nat -A goodwin_prerouting  -s 192.168.40.171 -j DNAT --to-destination $1
  sudo iptables -t nat -A goodwin_postrouting -d 192.168.40.171 -j SNAT --to-source 192.168.40.199
  sudo iptables -t nat -A goodwin_postrouting -d $1 -s 192.168.40.171 -p tcp -m multiport --dports 1501,1502 -j SNAT --to-source      192.168.40.199
  sudo iptables -t nat -A goodwin_prerouting  -s $1 -d 192.168.40.199 -p tcp -m multiport --sports 1501,1502 -j DNAT --to-destination 192.168.40.171
fi

